CREATE TABLE IF NOT EXISTS "public"."quests" (
    "id" BIGINT NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "image" TEXT NOT NULL,
    "total_points" BIGINT NOT NULL,
    "participant_count" BIGINT DEFAULT '0'::bigint NOT NULL,
    "start_date" timestamp with time zone
    "end_date" timestamp with time zone,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "updated_at" timestamp with time zone
);

ALTER TABLE "public"."quests" OWNER TO "postgres";

ALTER TABLE "public"."quests" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."quests_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."quests"
    ADD CONSTRAINT "quests_pkey" PRIMARY KEY ("id");

ALTER TABLE "public"."quests" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "view everyone" ON "public"."quests" FOR SELECT USING (true);

GRANT ALL ON TABLE "public"."quests" TO "anon";
GRANT ALL ON TABLE "public"."quests" TO "authenticated";
GRANT ALL ON TABLE "public"."quests" TO "service_role";
